/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskListItem } from '../../models/task-list-item';

export interface V1TaskListIdGet$Json$Params {
  id: string;
}

export function v1TaskListIdGet$Json(http: HttpClient, rootUrl: string, params: V1TaskListIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<TaskListItem>> {
  const rb = new RequestBuilder(rootUrl, v1TaskListIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TaskListItem>;
    })
  );
}

v1TaskListIdGet$Json.PATH = '/v1/TaskList/{id}';
