/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskListItem } from '../../models/task-list-item';

export interface V1TaskListGet$Plain$Params {
}

export function v1TaskListGet$Plain(http: HttpClient, rootUrl: string, params?: V1TaskListGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TaskListItem>>> {
  const rb = new RequestBuilder(rootUrl, v1TaskListGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TaskListItem>>;
    })
  );
}

v1TaskListGet$Plain.PATH = '/v1/TaskList';
