/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedTaskListResponse } from '../../models/paginated-task-list-response';

export interface V2TaskListGet$Plain$Params {
  start?: number;
  amount?: number;
}

export function v2TaskListGet$Plain(http: HttpClient, rootUrl: string, params?: V2TaskListGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedTaskListResponse>> {
  const rb = new RequestBuilder(rootUrl, v2TaskListGet$Plain.PATH, 'get');
  if (params) {
    rb.query('start', params.start, {});
    rb.query('amount', params.amount, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedTaskListResponse>;
    })
  );
}

v2TaskListGet$Plain.PATH = '/v2/TaskList';
