/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { V1TaskListGet$Plain$Params as V1TaskListGet$Plain$Params } from './fn/task-list/v-1-task-list-get-plain';
export { v1TaskListGet$Plain as v1TaskListGet$Plain } from './fn/task-list/v-1-task-list-get-plain';
export type { V1TaskListGet$Json$Params as V1TaskListGet$Json$Params } from './fn/task-list/v-1-task-list-get-json';
export { v1TaskListGet$Json as v1TaskListGet$Json } from './fn/task-list/v-1-task-list-get-json';
export type { V1TaskListPost$Plain$Params as V1TaskListPost$Plain$Params } from './fn/task-list/v-1-task-list-post-plain';
export { v1TaskListPost$Plain as v1TaskListPost$Plain } from './fn/task-list/v-1-task-list-post-plain';
export type { V1TaskListPost$Json$Params as V1TaskListPost$Json$Params } from './fn/task-list/v-1-task-list-post-json';
export { v1TaskListPost$Json as v1TaskListPost$Json } from './fn/task-list/v-1-task-list-post-json';
export type { V1TaskListIdGet$Plain$Params as V1TaskListIdGet$Plain$Params } from './fn/task-list/v-1-task-list-id-get-plain';
export { v1TaskListIdGet$Plain as v1TaskListIdGet$Plain } from './fn/task-list/v-1-task-list-id-get-plain';
export type { V1TaskListIdGet$Json$Params as V1TaskListIdGet$Json$Params } from './fn/task-list/v-1-task-list-id-get-json';
export { v1TaskListIdGet$Json as v1TaskListIdGet$Json } from './fn/task-list/v-1-task-list-id-get-json';
export type { V1TaskListIdPost$Params as V1TaskListIdPost$Params } from './fn/task-list/v-1-task-list-id-post';
export { v1TaskListIdPost as v1TaskListIdPost } from './fn/task-list/v-1-task-list-id-post';
