/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaskListItem } from '../models/task-list-item';
export interface PaginatedTaskListResponse {
  content?: Array<TaskListItem> | null;
  total?: number;
}
