/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { TaskListItem } from '../models/task-list-item';
import { v1TaskListGet$Json } from '../fn/task-list/v-1-task-list-get-json';
import { V1TaskListGet$Json$Params } from '../fn/task-list/v-1-task-list-get-json';
import { v1TaskListGet$Plain } from '../fn/task-list/v-1-task-list-get-plain';
import { V1TaskListGet$Plain$Params } from '../fn/task-list/v-1-task-list-get-plain';
import { v1TaskListIdGet$Json } from '../fn/task-list/v-1-task-list-id-get-json';
import { V1TaskListIdGet$Json$Params } from '../fn/task-list/v-1-task-list-id-get-json';
import { v1TaskListIdGet$Plain } from '../fn/task-list/v-1-task-list-id-get-plain';
import { V1TaskListIdGet$Plain$Params } from '../fn/task-list/v-1-task-list-id-get-plain';
import { v1TaskListIdPost } from '../fn/task-list/v-1-task-list-id-post';
import { V1TaskListIdPost$Params } from '../fn/task-list/v-1-task-list-id-post';
import { v1TaskListPost$Json } from '../fn/task-list/v-1-task-list-post-json';
import { V1TaskListPost$Json$Params } from '../fn/task-list/v-1-task-list-post-json';
import { v1TaskListPost$Plain } from '../fn/task-list/v-1-task-list-post-plain';
import { V1TaskListPost$Plain$Params } from '../fn/task-list/v-1-task-list-post-plain';

@Injectable({ providedIn: 'root' })
export class TaskListService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `v1TaskListGet()` */
  static readonly V1TaskListGetPath = '/v1/TaskList';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `v1TaskListGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  v1TaskListGet$Plain$Response(params?: V1TaskListGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<TaskListItem>>> {
    const obs = v1TaskListGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `v1TaskListGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  v1TaskListGet$Plain(params?: V1TaskListGet$Plain$Params, context?: HttpContext): Promise<Array<TaskListItem>> {
    const resp = this.v1TaskListGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<TaskListItem>>): Array<TaskListItem> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `v1TaskListGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  v1TaskListGet$Json$Response(params?: V1TaskListGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<TaskListItem>>> {
    const obs = v1TaskListGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `v1TaskListGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  v1TaskListGet$Json(params?: V1TaskListGet$Json$Params, context?: HttpContext): Promise<Array<TaskListItem>> {
    const resp = this.v1TaskListGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<TaskListItem>>): Array<TaskListItem> => r.body);
  }

  /** Path part for operation `v1TaskListPost()` */
  static readonly V1TaskListPostPath = '/v1/TaskList';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `v1TaskListPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  v1TaskListPost$Plain$Response(params?: V1TaskListPost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<string>> {
    const obs = v1TaskListPost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `v1TaskListPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  v1TaskListPost$Plain(params?: V1TaskListPost$Plain$Params, context?: HttpContext): Promise<string> {
    const resp = this.v1TaskListPost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<string>): string => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `v1TaskListPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  v1TaskListPost$Json$Response(params?: V1TaskListPost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<string>> {
    const obs = v1TaskListPost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `v1TaskListPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  v1TaskListPost$Json(params?: V1TaskListPost$Json$Params, context?: HttpContext): Promise<string> {
    const resp = this.v1TaskListPost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<string>): string => r.body);
  }

  /** Path part for operation `v1TaskListIdGet()` */
  static readonly V1TaskListIdGetPath = '/v1/TaskList/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `v1TaskListIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  v1TaskListIdGet$Plain$Response(params: V1TaskListIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<TaskListItem>> {
    const obs = v1TaskListIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `v1TaskListIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  v1TaskListIdGet$Plain(params: V1TaskListIdGet$Plain$Params, context?: HttpContext): Promise<TaskListItem> {
    const resp = this.v1TaskListIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<TaskListItem>): TaskListItem => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `v1TaskListIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  v1TaskListIdGet$Json$Response(params: V1TaskListIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<TaskListItem>> {
    const obs = v1TaskListIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `v1TaskListIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  v1TaskListIdGet$Json(params: V1TaskListIdGet$Json$Params, context?: HttpContext): Promise<TaskListItem> {
    const resp = this.v1TaskListIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<TaskListItem>): TaskListItem => r.body);
  }

  /** Path part for operation `v1TaskListIdPost()` */
  static readonly V1TaskListIdPostPath = '/v1/TaskList/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `v1TaskListIdPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  v1TaskListIdPost$Response(params: V1TaskListIdPost$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = v1TaskListIdPost(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `v1TaskListIdPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  v1TaskListIdPost(params: V1TaskListIdPost$Params, context?: HttpContext): Promise<void> {
    const resp = this.v1TaskListIdPost$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
